{
	"class": "vulnerability",
	"id": "oval:com.ubuntu.xenial:def:201517830000000",
	"version": "1",
	"metadata": {
		"Title": "CVE-2015-1783 on Ubuntu 16.04 ESM (xenial) - medium.",
		"Description": "The prefix variable in the get_or_define_ns function in Lasso before commit 6d854cef4211cdcdbc7446c978f23ab859847cdd allows remote attackers to cause a denial of service (uninitialized memory access and application crash) via unspecified vectors.\n\nUpdate Instructions:\n\nRun `sudo pro fix CVE-2015-1783` to fix the vulnerability. The problem can be corrected\nby updating your system to the following package versions:\n\nliblasso-perl - 2.4.1-1build1\nliblasso3 - 2.4.1-1build1\nphp5-lasso - 2.4.1-1build1\npython-lasso - 2.4.1-1build1\nNo subscription required",
		"affected": {
			"family": "unix",
			"Platform": "Ubuntu 16.04 ESM"
		},
		"reference": {
			"source": "CVE",
			"ref_id": "CVE-2015-1783",
			"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-1783"
		},
		"advisory": {
			"Severity": "Medium",
			"Rights": "Copyright (C) 2017 Canonical Ltd.",
			"PublicDate": "2017-08-11 21:29:00 UTC",
			"Bug": null,
			"cve": {
				"text": "CVE-2015-1783",
				"href": "https://ubuntu.com/security/CVE-2015-1783",
				"public": "20170811",
				"cvss_score": "7.5",
				"cvss_vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
			},
			"PublicDateAtUsn": "",
			"AssignedTo": "",
			"DiscoveredBy": "",
			"Crd": "",
			"Ref": null
		}
	},
	"notes": {
		"Note": ""
	},
	"criteria": {
		"criterions": [
			{
				"test_ref": "oval:com.ubuntu.xenial:tst:201517830000000",
				"comment": "lasso package in xenial, is related to the CVE in some way and has been fixed (note: '2.4.1-1build1')."
			}
		]
	}
}
