{
	"class": "vulnerability",
	"id": "oval:com.ubuntu.focal:def:20040128800000",
	"version": "1",
	"metadata": {
		"title": "nagios4",
		"reference": {
			"source": "Package",
			"ref_id": "nagios4",
			"ref_url": "https://launchpad.net/ubuntu/+source/nagios4"
		},
		"description": "host/service/network monitoring and management system",
		"affected": {
			"family": "unix",
			"platform": "Ubuntu 20.04 LTS"
		},
		"advisory": {
			"rights": "Copyright (C) 2024 Canonical Ltd.",
			"component": "universe",
			"current_version": "4.3.4-3ubuntu0.1",
			"cve": [
				{
					"text": "CVE-2018-18245",
					"href": "https://ubuntu.com/security/CVE-2018-18245",
					"priority": "low",
					"public": "20181217",
					"cvss_score": "5.4",
					"cvss_vector": "CVSS:3.0/AV:N/AC:L/PR:L/UI:R/S:C/C:L/I:L/A:N",
					"cvss_severity": "medium",
					"test_ref": "oval:com.ubuntu.focal:tst:20040128800000"
				}
			]
		}
	},
	"criteria": {
		"criterias": [
			{
				"operator": "OR",
				"criterions": [
					{
						"test_ref": "oval:com.ubuntu.focal:tst:20040128800000",
						"comment": "(CVE-2018-18245) nagios4 package in focal, is related to the CVE in some way and has been fixed (note: '4.3.4-3')."
					}
				]
			}
		]
	}
}
