{
	"class": "vulnerability",
	"id": "oval:com.ubuntu.xenial:def:2023335950000000",
	"version": "1",
	"metadata": {
		"title": "CVE-2023-33595 on Ubuntu 16.04 FIPS Compliant (xenial) - medium",
		"description": "CPython v3.12.0 alpha 7 was discovered to contain a heap use-after-free viathe function ascii_decode at /Objects/unicodeobject.c.",
		"affected": {
			"family": "unix",
			"platform": "Ubuntu 16.04 FIPS Compliant"
		},
		"reference": {
			"source": "CVE",
			"ref_id": "CVE-2023-33595",
			"ref_url": "https://www.cve.org/CVERecord?id=CVE-2023-33595"
		},
		"advisory": {
			"severity": "Medium",
			"rights": "Copyright (C) 2023 Canonical Ltd.",
			"public_date": "2023-06-07 20:15:00 UTC",
			"cve": {
				"text": "CVE-2023-33595",
				"href": "https://ubuntu.com/security/CVE-2023-33595",
				"public": "20230607",
				"cvss_score": "5.5",
				"cvss_vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H"
			}
		}
	},
	"notes": {},
	"criteria": {
		"criterias": [
			{
				"operator": "OR",
				"criterions": [
					{
						"test_ref": "oval:com.ubuntu.xenial:tst:200745590000000",
						"comment": "python2.7: while related to the CVE in some way, a decision has been made to ignore this issue (note: 'end of standard support')."
					},
					{
						"test_ref": "oval:com.ubuntu.xenial:tst:200745590000010",
						"comment": "python3.5: while related to the CVE in some way, a decision has been made to ignore this issue (note: 'end of standard support')."
					}
				]
			}
		]
	}
}
