{
	"class": "patch",
	"id": "oval:com.ubuntu.impish:def:52691000000",
	"version": "1",
	"metadata": {
		"title": "5269-1 -- Django vulnerabilities",
		"description": "Keryn Knight discovered that Django incorrectly handled certain template tags. A remote attacker could possibly use this issue to perform a cross-site scripting attack. (CVE-2022-22818)  Alan Ryan discovered that Django incorrectly handled file uploads. A remote attacker could possibly use this issue to cause Django to hang, resulting in a denial of service. (CVE-2022-23833)  Update Instructions:  Run `sudo ua fix USN-5269-1` to fix the vulnerability. The problem can be corrected by updating your system to the following package versions:  python3-django - 2:2.2.24-1ubuntu1.3 python-django-doc - 2:2.2.24-1ubuntu1.3 No subscription required",
		"affected": {
			"family": "unix",
			"platform": "Ubuntu 21.10"
		},
		"reference": [
			{
				"source": "USN",
				"ref_id": "USN-5269-1",
				"ref_url": "https://ubuntu.com/security/notices/USN-5269-1"
			},
			{
				"source": "CVE",
				"ref_id": "CVE-2022-22818",
				"ref_url": "https://ubuntu.com/security/CVE-2022-22818"
			},
			{
				"source": "CVE",
				"ref_id": "CVE-2022-23833",
				"ref_url": "https://ubuntu.com/security/CVE-2022-23833"
			}
		],
		"advisory": {
			"from": "security@ubuntu.com",
			"severity": "Medium",
			"issued": {
				"date": "2022-02-03"
			}
		}
	},
	"criteria": {
		"operator": "OR",
		"criterions": [
			{
				"test_ref": "oval:com.ubuntu.impish:tst:526910000000",
				"comment": "Interim Release"
			}
		]
	}
}
