{
	"class": "vulnerability",
	"id": "oval:com.ubuntu.bionic:def:18040183100000",
	"version": "1",
	"metadata": {
		"title": "python-numpy",
		"reference": {
			"source": "Package",
			"ref_id": "python-numpy",
			"ref_url": "https://launchpad.net/ubuntu/+source/python-numpy"
		},
		"description": "Numerical Python adds a fast array facility to the Python language",
		"affected": {
			"family": "unix",
			"platform": "Ubuntu Pro FIPS 18.04 LTS"
		},
		"advisory": {
			"rights": "Copyright (C) 2025 Canonical Ltd.",
			"component": "main",
			"current_version": "1:1.13.3-2ubuntu1",
			"cve": [
				{
					"text": "CVE-2014-1859",
					"href": "https://ubuntu.com/security/CVE-2014-1859",
					"priority": "low",
					"public": "20180108",
					"cvss_score": "5.5",
					"cvss_vector": "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N",
					"cvss_severity": "medium",
					"test_ref": "oval:com.ubuntu.bionic:tst:18040183100000"
				}
			]
		}
	},
	"criteria": {
		"criterias": [
			{
				"operator": "OR",
				"criterions": [
					{
						"test_ref": "oval:com.ubuntu.bionic:tst:18040183100000",
						"comment": "(CVE-2014-1859) python-numpy package in bionic, is related to the CVE in some way and has been fixed (note: '1:1.8.1~rc1-1')."
					}
				]
			}
		]
	}
}
