{
	"class": "vulnerability",
	"id": "oval:com.ubuntu.focal:def:2019155220000000",
	"version": "1",
	"metadata": {
		"Title": "CVE-2019-15522 on Ubuntu 20.04 LTS (focal) - medium",
		"Description": "An issue was discovered in LINBIT csync2 through 2.0. csync_daemon_sessionin daemon.c neglects to force a failure of a hello command when theconfiguration requires use of SSL.",
		"affected": {
			"family": "unix",
			"Platform": "Ubuntu 20.04 LTS"
		},
		"reference": {
			"source": "CVE",
			"ref_id": "CVE-2019-15522",
			"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-15522"
		},
		"advisory": {
			"Severity": "Medium",
			"Rights": "Copyright (C) 2020 Canonical Ltd.",
			"PublicDate": "2020-03-20 21:15:00 UTC",
			"Bug": null,
			"cve": {
				"text": "CVE-2019-15522",
				"href": "https://ubuntu.com/security/CVE-2019-15522",
				"public": "20200320",
				"cvss_score": "9.8",
				"cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
			},
			"PublicDateAtUsn": "",
			"AssignedTo": "pfsmorigo",
			"DiscoveredBy": "",
			"Crd": "",
			"Ref": null
		}
	},
	"notes": {
		"Note": ""
	},
	"criteria": {
		"criterias": [
			{
				"operator": "OR",
				"criterions": [
					{
						"test_ref": "oval:com.ubuntu.focal:tst:2019155220000000",
						"comment": "csync2 package in focal is affected and needs fixing."
					}
				]
			}
		]
	}
}
