{
	"class": "vulnerability",
	"id": "oval:com.ubuntu.kinetic:def:202135140000000",
	"version": "1",
	"metadata": {
		"title": "CVE-2021-3514 on Ubuntu 22.10 (kinetic) - medium.",
		"description": "When using a sync_repl client in 389-ds-base, an authenticated attacker can cause a NULL pointer dereference using a specially crafted query, causing a crash.\n\nUpdate Instructions:\n\nRun `sudo pro fix CVE-2021-3514` to fix the vulnerability. The problem can be corrected\nby updating your system to the following package versions:\n\n389-ds - 1.4.4.11-2\n389-ds-base - 1.4.4.11-2\n389-ds-base-libs - 1.4.4.11-2\ncockpit-389-ds - 1.4.4.11-2\npython3-lib389 - 1.4.4.11-2\nNo subscription required",
		"affected": {
			"family": "unix",
			"platform": "Ubuntu 22.10"
		},
		"reference": {
			"source": "CVE",
			"ref_id": "CVE-2021-3514",
			"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3514"
		},
		"advisory": {
			"severity": "Medium",
			"rights": "Copyright (C) 2021 Canonical Ltd.",
			"public_date": "2021-05-28 15:15:00 UTC",
			"cve": {
				"text": "CVE-2021-3514",
				"href": "https://ubuntu.com/security/CVE-2021-3514",
				"severity": "medium",
				"public": "20210528",
				"cvss_score": "6.5",
				"cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
				"usns": "5231-1"
			},
			"public_date_at_usn": "2021-05-28 15:15:00 UTC"
		}
	},
	"notes": {},
	"criteria": {
		"criterions": [
			{
				"test_ref": "oval:com.ubuntu.kinetic:tst:202135140000000",
				"comment": "389-ds-base package in kinetic, is related to the CVE in some way and has been fixed (note: '1.4.4.11-2')."
			}
		]
	}
}
