{
	"class": "vulnerability",
	"id": "oval:com.ubuntu.noble:def:24040168400000",
	"version": "1",
	"metadata": {
		"title": "python3.12",
		"reference": {
			"source": "Package",
			"ref_id": "python3.12",
			"ref_url": "https://launchpad.net/ubuntu/+source/python3.12"
		},
		"description": "An interactive high-level object-oriented language",
		"affected": {
			"family": "unix",
			"platform": "Ubuntu 24.04 LTS"
		},
		"advisory": {
			"rights": "Copyright (C) 2024 Canonical Ltd.",
			"component": "main",
			"current_version": "3.12.3-1ubuntu0.3",
			"cve": [
				{
					"text": "CVE-2022-48564",
					"href": "https://ubuntu.com/security/CVE-2022-48564",
					"priority": "medium",
					"public": "20230822",
					"cvss_score": "6.5",
					"cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
					"cvss_severity": "medium",
					"test_ref": "oval:com.ubuntu.noble:tst:24040168400000",
					"usns": "6513-1,6891-1"
				},
				{
					"text": "CVE-2022-48565",
					"href": "https://ubuntu.com/security/CVE-2022-48565",
					"priority": "medium",
					"public": "20230822",
					"cvss_score": "9.8",
					"cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
					"cvss_severity": "critical",
					"test_ref": "oval:com.ubuntu.noble:tst:24040168400010",
					"usns": "6354-1,6891-1"
				},
				{
					"text": "CVE-2023-6507",
					"href": "https://ubuntu.com/security/CVE-2023-6507",
					"priority": "medium",
					"public": "20231208",
					"cvss_score": "4.9",
					"cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:N/I:H/A:N",
					"cvss_severity": "medium",
					"test_ref": "oval:com.ubuntu.noble:tst:24040168400020",
					"usns": "6891-1"
				},
				{
					"text": "CVE-2023-6597",
					"href": "https://ubuntu.com/security/CVE-2023-6597",
					"priority": "medium",
					"public": "20240319",
					"test_ref": "oval:com.ubuntu.noble:tst:24040168400030"
				},
				{
					"text": "CVE-2023-27043",
					"href": "https://ubuntu.com/security/CVE-2023-27043",
					"priority": "medium",
					"public": "20230419",
					"cvss_score": "5.3",
					"cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
					"cvss_severity": "medium",
					"test_ref": "oval:com.ubuntu.noble:tst:24040168400040",
					"usns": "7015-1,7015-3,7015-4"
				},
				{
					"text": "CVE-2023-40217",
					"href": "https://ubuntu.com/security/CVE-2023-40217",
					"priority": "medium",
					"public": "20230825",
					"cvss_score": "5.3",
					"cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
					"cvss_severity": "medium",
					"test_ref": "oval:com.ubuntu.noble:tst:24040168400000",
					"usns": "6513-1,6513-2,6891-1"
				},
				{
					"text": "CVE-2023-41105",
					"href": "https://ubuntu.com/security/CVE-2023-41105",
					"priority": "medium",
					"public": "20230823",
					"cvss_score": "7.5",
					"cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
					"cvss_severity": "high",
					"test_ref": "oval:com.ubuntu.noble:tst:24040168400000",
					"usns": "6547-1,6891-1"
				},
				{
					"text": "CVE-2024-0397",
					"href": "https://ubuntu.com/security/CVE-2024-0397",
					"priority": "medium",
					"public": "20240617",
					"test_ref": "oval:com.ubuntu.noble:tst:24040168400030"
				},
				{
					"text": "CVE-2024-0450",
					"href": "https://ubuntu.com/security/CVE-2024-0450",
					"priority": "medium",
					"public": "20240319",
					"test_ref": "oval:com.ubuntu.noble:tst:24040168400030"
				},
				{
					"text": "CVE-2024-4032",
					"href": "https://ubuntu.com/security/CVE-2024-4032",
					"priority": "low",
					"public": "20240617",
					"test_ref": "oval:com.ubuntu.noble:tst:24040168400050"
				},
				{
					"text": "CVE-2024-5642",
					"href": "https://ubuntu.com/security/CVE-2024-5642",
					"priority": "low",
					"public": "20240627",
					"test_ref": "oval:com.ubuntu.noble:tst:24040168400030"
				},
				{
					"text": "CVE-2024-6232",
					"href": "https://ubuntu.com/security/CVE-2024-6232",
					"priority": "medium",
					"public": "20240903",
					"cvss_score": "7.5",
					"cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
					"cvss_severity": "high",
					"test_ref": "oval:com.ubuntu.noble:tst:24040168400040",
					"usns": "7015-1,7015-2,7015-5"
				},
				{
					"text": "CVE-2024-6923",
					"href": "https://ubuntu.com/security/CVE-2024-6923",
					"priority": "medium",
					"public": "20240801",
					"test_ref": "oval:com.ubuntu.noble:tst:24040168400040"
				},
				{
					"text": "CVE-2024-7592",
					"href": "https://ubuntu.com/security/CVE-2024-7592",
					"priority": "low",
					"public": "20240819",
					"cvss_score": "7.5",
					"cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
					"cvss_severity": "high",
					"test_ref": "oval:com.ubuntu.noble:tst:24040168400040",
					"usns": "7015-1,7015-2"
				},
				{
					"text": "CVE-2024-8088",
					"href": "https://ubuntu.com/security/CVE-2024-8088",
					"priority": "medium",
					"public": "20240822",
					"test_ref": "oval:com.ubuntu.noble:tst:24040168400040"
				},
				{
					"text": "CVE-2024-9287",
					"href": "https://ubuntu.com/security/CVE-2024-9287",
					"priority": "medium",
					"public": "20241022",
					"test_ref": "oval:com.ubuntu.noble:tst:24040168400060"
				},
				{
					"text": "CVE-2024-11168",
					"href": "https://ubuntu.com/security/CVE-2024-11168",
					"priority": "medium",
					"public": "20241112",
					"test_ref": "oval:com.ubuntu.noble:tst:24040168400030"
				}
			]
		}
	},
	"criteria": {
		"criterias": [
			{
				"operator": "OR",
				"criterions": [
					{
						"test_ref": "oval:com.ubuntu.noble:tst:24040168400000",
						"comment": "(CVE-2022-48564) python3.12 package in noble, is related to the CVE in some way and has been fixed (note: '3.12.0-6')."
					},
					{
						"test_ref": "oval:com.ubuntu.noble:tst:24040168400010",
						"comment": "(CVE-2022-48565) python3.12 package in noble, is related to the CVE in some way and has been fixed (note: '3.12.0~a7-1')."
					},
					{
						"test_ref": "oval:com.ubuntu.noble:tst:24040168400020",
						"comment": "(CVE-2023-6507) python3.12 package in noble, is related to the CVE in some way and has been fixed (note: '3.12.1-2')."
					},
					{
						"test_ref": "oval:com.ubuntu.noble:tst:24040168400030",
						"comment": "(CVE-2023-6597) python3.12 package in noble, is related to the CVE in some way and has been fixed (note: '3.12.3-1')."
					},
					{
						"test_ref": "oval:com.ubuntu.noble:tst:24040168400040",
						"comment": "(CVE-2023-27043) python3.12 package in noble was vulnerable but has been fixed (note: '3.12.3-1ubuntu0.2')."
					},
					{
						"test_ref": "oval:com.ubuntu.noble:tst:24040168400000",
						"comment": "(CVE-2023-40217) python3.12 package in noble, is related to the CVE in some way and has been fixed (note: '3.12.0-6')."
					},
					{
						"test_ref": "oval:com.ubuntu.noble:tst:24040168400000",
						"comment": "(CVE-2023-41105) python3.12 package in noble, is related to the CVE in some way and has been fixed (note: '3.12.0-6')."
					},
					{
						"test_ref": "oval:com.ubuntu.noble:tst:24040168400030",
						"comment": "(CVE-2024-0397) python3.12 package in noble, is related to the CVE in some way and has been fixed (note: '3.12.3-1')."
					},
					{
						"test_ref": "oval:com.ubuntu.noble:tst:24040168400030",
						"comment": "(CVE-2024-0450) python3.12 package in noble, is related to the CVE in some way and has been fixed (note: '3.12.3-1')."
					},
					{
						"test_ref": "oval:com.ubuntu.noble:tst:24040168400050",
						"comment": "(CVE-2024-4032) python3.12 package in noble was vulnerable but has been fixed (note: '3.12.3-1ubuntu0.1')."
					},
					{
						"test_ref": "oval:com.ubuntu.noble:tst:24040168400030",
						"comment": "(CVE-2024-5642) python3.12 package in noble, is related to the CVE in some way and has been fixed (note: '3.12.3-1')."
					},
					{
						"test_ref": "oval:com.ubuntu.noble:tst:24040168400040",
						"comment": "(CVE-2024-6232) python3.12 package in noble was vulnerable but has been fixed (note: '3.12.3-1ubuntu0.2')."
					},
					{
						"test_ref": "oval:com.ubuntu.noble:tst:24040168400040",
						"comment": "(CVE-2024-6923) python3.12 package in noble was vulnerable but has been fixed (note: '3.12.3-1ubuntu0.2')."
					},
					{
						"test_ref": "oval:com.ubuntu.noble:tst:24040168400040",
						"comment": "(CVE-2024-7592) python3.12 package in noble was vulnerable but has been fixed (note: '3.12.3-1ubuntu0.2')."
					},
					{
						"test_ref": "oval:com.ubuntu.noble:tst:24040168400040",
						"comment": "(CVE-2024-8088) python3.12 package in noble was vulnerable but has been fixed (note: '3.12.3-1ubuntu0.2')."
					},
					{
						"test_ref": "oval:com.ubuntu.noble:tst:24040168400060",
						"comment": "(CVE-2024-9287) python3.12 package in noble was vulnerable but has been fixed (note: '3.12.3-1ubuntu0.3')."
					},
					{
						"test_ref": "oval:com.ubuntu.noble:tst:24040168400030",
						"comment": "(CVE-2024-11168) python3.12 package in noble, is related to the CVE in some way and has been fixed (note: '3.12.3-1')."
					}
				]
			}
		]
	}
}
