{
	"class": "vulnerability",
	"id": "oval:com.ubuntu.bionic:def:2017183420000000",
	"version": "1",
	"metadata": {
		"title": "CVE-2017-18342 on Ubuntu 18.04 FIPS Certified (bionic) - low",
		"description": "In PyYAML before 5.1, the yaml.load() API could execute arbitrary code ifused with untrusted data. The load() function has been deprecated inversion 5.1 and the 'UnsafeLoader' has been introduced for backwardcompatibility with the function.",
		"affected": {
			"family": "unix",
			"platform": "Ubuntu 18.04 FIPS Certified"
		},
		"reference": {
			"source": "CVE",
			"ref_id": "CVE-2017-18342",
			"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-18342"
		},
		"advisory": {
			"severity": "Low",
			"rights": "Copyright (C) 2018 Canonical Ltd.",
			"public_date": "2018-06-27 12:29:00 UTC",
			"bug": [
				"http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=902878"
			],
			"cve": {
				"text": "CVE-2017-18342",
				"href": "https://ubuntu.com/security/CVE-2017-18342",
				"public": "20180627",
				"cvss_score": "9.8",
				"cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
			}
		}
	},
	"notes": {},
	"criteria": {
		"criterias": [
			{
				"operator": "OR",
				"criterions": [
					{
						"test_ref": "oval:com.ubuntu.bionic:tst:2017183420000000",
						"comment": "pyyaml: while related to the CVE in some way, a decision has been made to ignore this issue."
					}
				]
			}
		]
	}
}
