{
	"class": "vulnerability",
	"id": "oval:com.ubuntu.xenial:def:202135200000000",
	"version": "1",
	"metadata": {
		"Title": "CVE-2021-3520 on Ubuntu 16.04 FIPS Certified (xenial) - medium.",
		"Description": "There's a flaw in lz4. An attacker who submits a crafted file to an application linked with lz4 may be able to trigger an integer overflow, leading to calling of memmove() on a negative size argument, causing an out-of-bounds write and/or a crash. The greatest impact of this flaw is to availability, with some potential impact to confidentiality and integrity as well.",
		"affected": {
			"family": "unix",
			"Platform": "Ubuntu 16.04 FIPS Certified"
		},
		"reference": {
			"source": "CVE",
			"ref_id": "CVE-2021-3520",
			"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3520"
		},
		"advisory": {
			"Severity": "Medium",
			"Rights": "Copyright (C) 2021 Canonical Ltd.",
			"PublicDate": "2021-04-30 00:00:00 UTC",
			"Bug": [
				"https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=987856"
			],
			"cve": {
				"text": "CVE-2021-3520",
				"href": "https://ubuntu.com/security/CVE-2021-3520",
				"public": "20210430",
				"cvss_score": "9.8",
				"cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
				"usns": "4968-1,4968-2"
			},
			"PublicDateAtUsn": "2021-04-30 00:00:00 UTC",
			"AssignedTo": "mdeslaur",
			"DiscoveredBy": "",
			"Crd": "",
			"Ref": null
		}
	},
	"notes": {
		"Note": ""
	},
	"criteria": {
		"criterions": [
			{
				"test_ref": "oval:com.ubuntu.xenial:tst:2019175430000000",
				"comment": "lz4: while related to the CVE in some way, a decision has been made to ignore this issue (note: 'end of standard support, was needs-triage')."
			}
		]
	}
}
