{
	"class": "vulnerability",
	"id": "oval:com.ubuntu.hirsute:def:201976530000000",
	"version": "1",
	"metadata": {
		"Title": "CVE-2019-7653 on Ubuntu 21.04 (hirsute) - medium.",
		"Description": "The Debian python-rdflib-tools 4.2.2-1 package for RDFLib 4.2.2 has CLI tools that can load Python modules from the current working directory, allowing code injection, because \"python -m\" looks in this directory, as demonstrated by rdf2dot. This issue is specific to use of the debian/scripts directory.",
		"affected": {
			"family": "unix",
			"Platform": "Ubuntu 21.04"
		},
		"reference": {
			"source": "CVE",
			"ref_id": "CVE-2019-7653",
			"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-7653"
		},
		"advisory": {
			"Severity": "Medium",
			"Rights": "Copyright (C) 2019 Canonical Ltd.",
			"PublicDate": "2019-02-09 03:29:00 UTC",
			"Bug": [
				"http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=921751"
			],
			"cve": {},
			"PublicDateAtUsn": "2019-02-09 03:29:00 UTC",
			"AssignedTo": "",
			"DiscoveredBy": "",
			"Crd": "",
			"Ref": [
				"http://people.canonical.com/~ubuntu-security/cve/2019/CVE-2019-7653.html",
				"https://bugs.debian.org/921751",
				"https://ubuntu.com/security/notices/USN-4535-1"
			]
		}
	},
	"notes": {
		"Note": "mdeslaur> python-rdflib-tools binary package is in universe"
	},
	"criteria": {
		"criterions": [
			{
				"test_ref": "oval:com.ubuntu.hirsute:tst:201976530000000",
				"comment": "rdflib package in hirsute, is related to the CVE in some way and has been fixed (note: '4.2.2-2')."
			}
		]
	}
}
