{
	"class": "vulnerability",
	"id": "oval:com.ubuntu.mantic:def:201971640000000",
	"version": "1",
	"metadata": {
		"Title": "CVE-2019-7164 on Ubuntu 23.10 (mantic) - low",
		"Description": "SQLAlchemy through 1.2.17 and 1.3.x through 1.3.0b2 allows SQL Injectionvia the order_by parameter.\n\n    Update Instructions:\n\n    Run `sudo pro fix CVE-2019-7164` to fix the vulnerability. The problem can be corrected\n    by updating your system to the following package versions:\n\npython3-sqlalchemy - 1.2.18+ds1-2ubuntu1\npython3-sqlalchemy-ext - 1.2.18+ds1-2ubuntu1\nNo subscription required",
		"affected": {
			"family": "unix",
			"Platform": "Ubuntu 23.10"
		},
		"reference": {
			"source": "CVE",
			"ref_id": "CVE-2019-7164",
			"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-7164"
		},
		"advisory": {
			"Severity": "Low",
			"Rights": "Copyright (C) 2019 Canonical Ltd.",
			"PublicDate": "2019-02-20 00:29:00 UTC",
			"Bug": [
				"https://github.com/sqlalchemy/sqlalchemy/issues/4481",
				"http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=922669",
				"https://github.com/sqlalchemy/sqlalchemy/issues/4538 (example regression)"
			],
			"cve": {
				"text": "CVE-2019-7164",
				"href": "https://ubuntu.com/security/CVE-2019-7164",
				"public": "20190220",
				"cvss_score": "9.8",
				"cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
			},
			"PublicDateAtUsn": "",
			"AssignedTo": "",
			"DiscoveredBy": "",
			"Crd": "",
			"Ref": null
		}
	},
	"notes": {
		"Note": ""
	},
	"criteria": {
		"criterias": [
			{
				"operator": "OR",
				"criterions": [
					{
						"test_ref": "oval:com.ubuntu.mantic:tst:201971640000000",
						"comment": "sqlalchemy package in mantic, is related to the CVE in some way and has been fixed (note: '1.2.18+ds1-2ubuntu1')."
					}
				]
			}
		]
	}
}
