{
	"class": "vulnerability",
	"id": "oval:com.ubuntu.trusty:def:2022485660000000",
	"version": "1",
	"metadata": {
		"title": "CVE-2022-48566 on Ubuntu 14.04 LTS (trusty) - medium",
		"description": "An issue was discovered in compare_digest in Lib/hmac.py in Python through3.9.1. Constant-time-defeating optimisations were possible in theaccumulator variable in hmac.compare_digest.\n\n    Update Instructions:\n\n    Run `sudo pro fix CVE-2022-48566` to fix the vulnerability. The problem can be corrected\n    by updating your system to the following package versions:\n\nidle-python3.5 - 3.5.2-2ubuntu0~16.04.4~14.04.1+esm1\nlibpython3.5 - 3.5.2-2ubuntu0~16.04.4~14.04.1+esm1\nlibpython3.5-minimal - 3.5.2-2ubuntu0~16.04.4~14.04.1+esm1\nlibpython3.5-stdlib - 3.5.2-2ubuntu0~16.04.4~14.04.1+esm1\nlibpython3.5-testsuite - 3.5.2-2ubuntu0~16.04.4~14.04.1+esm1\npython3.5 - 3.5.2-2ubuntu0~16.04.4~14.04.1+esm1\npython3.5-examples - 3.5.2-2ubuntu0~16.04.4~14.04.1+esm1\npython3.5-minimal - 3.5.2-2ubuntu0~16.04.4~14.04.1+esm1\npython3.5-venv - 3.5.2-2ubuntu0~16.04.4~14.04.1+esm1\nAvailable with Ubuntu Pro (Infra-only): https://ubuntu.com/pro",
		"affected": {
			"family": "unix",
			"platform": "Ubuntu 14.04 LTS"
		},
		"reference": {
			"source": "CVE",
			"ref_id": "CVE-2022-48566",
			"ref_url": "https://www.cve.org/CVERecord?id=CVE-2022-48566"
		},
		"advisory": {
			"severity": "Medium",
			"rights": "Copyright (C) 2023 Canonical Ltd.",
			"public_date": "2023-08-22 19:16:00 UTC",
			"cve": {
				"text": "CVE-2022-48566",
				"href": "https://ubuntu.com/security/CVE-2022-48566",
				"public": "20230822",
				"cvss_score": "5.9",
				"cvss_vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N",
				"usns": "6400-1,6891-1"
			},
			"public_date_at_usn": "2023-08-22 19:16:00 UTC",
			"ref": [
				"https://ubuntu.com/security/notices/USN-6400-1",
				"https://ubuntu.com/security/notices/USN-6891-1"
			]
		}
	},
	"notes": {},
	"criteria": {
		"criterias": [
			{
				"operator": "OR",
				"criterions": [
					{
						"test_ref": "oval:com.ubuntu.trusty:tst:200745590000000",
						"comment": "python2.7 package in trusty is affected and may need fixing."
					},
					{
						"test_ref": "oval:com.ubuntu.trusty:tst:200745590000010",
						"comment": "python3.4 package in trusty is affected and needs fixing."
					},
					{
						"test_ref": "oval:com.ubuntu.trusty:tst:2015201070000020",
						"comment": "python3.5 package in trusty was vulnerable but has been fixed (note: '3.5.2-2ubuntu0~16.04.4~14.04.1+esm1')."
					}
				]
			}
		]
	}
}
